#! /bin/bash

message ()
{
	echo -e "\e[94m$1\e[39m"
}

error ()
{
	echo -e "\e[91m$1\e[39m"
}


BRANCH=thud
DEST=${HOME}/yocto-enuc-${BRANCH}

mkdir ${DEST}
cd ${DEST}

message "Clone repositories"
git clone https://github.com/ROJ-ITALY/sources.git -b $BRANCH
cd sources
git submodule init
git submodule update

message "Copy base-roj-platform into base dir"
cp -r base-roj-platform base

cd ..

message "Create link"
ln -s sources/fsl-community-bsp-base/README README
ln -s sources/fsl-community-bsp-base/setup-environment setup-environment
ln -s sources/meta-fsl-bsp-release/imx/README README-IMXBSP
ln -s sources/meta-fsl-bsp-release/imx/tools/fsl-setup-release.sh fsl-setup-release.sh

message "Yocto environment created."
