#! /bin/sh
#
# Download packages to use Yocto Project. This packages have to be also checked on the new Ubuntu 16.04 machine.
#


echo "Set the default shell to bash. Not use dash."
sudo dpkg-reconfigure dash

echo "Install packages to support Yocto Project."
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping
sudo apt-get install make xsltproc docbook-utils fop dblatex xmlto
sudo apt-get install python-git
sudo apt-get install libncurses5-dev

