#! /bin/sh
#
# Download packages to use Yocto Project. This packages have to be also checked on the new Ubuntu 16.04 machine.
#


echo "Set the default shell to bash. Not use dash."
sudo dpkg-reconfigure dash

echo "Install packages to support Yocto Project."
sudo apt-get install sed wget cvs subversion git-core coreutils unzip texi2html texinfo libsdl1.2-dev docbook-utils gawk python-pysqlite2 diffstat help2man make gcc build-essential g++ \
desktop-file-utils chrpath libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake groff libtool xterm lzop vim ssh screen xz-utils meld geany picocom minicom u-boot-tools libncurses5-dev \
xinetd tftpd tftp nfs-common nfs-kernel-server

