#! /bin/sh
#
# Update a build tree for Yocto Project
#

BRANCH=krogoth
DEST=${HOME}/yocto-${BRANCH}-smarc/sources

echo "Update repositories."

echo "Update poky. Wait..."
cd ${DEST}/poky
git pull
echo "Updated."

echo "Update meta-openembedded. Wait..."
cd ..
cd ${DEST}/meta-openembedded
git pull
echo "Updated."

echo "Update fsl-arm. Wait..."
cd ..
cd ${DEST}/meta-fsl-arm
git pull
echo "Updated."

echo "Update fsl-arm-extra. Wait..."
cd ..
cd ${DEST}/meta-fsl-arm-extra
git pull
echo "Updated."

echo "Update fsl-arm-extra. Wait..."
cd ..
cd ${DEST}/meta-fsl-demos
git pull
echo "Updated."

echo "Update fsl-community-bsp-base. Wait..."
cd ..
cd ${DEST}/fsl-community-bsp-base
git pull
cp -R ../fsl-community-bsp-base/* ../base/
cp ../base/README ../../README
cp ../base/setup-environment ../../setup-environment
echo "Updated."

echo "Update meta-qt5. Wait..."
cd ..
cd ${DEST}/meta-qt5
git pull
echo "Updated."

echo "Update meta-roj-platform. Wait..."
cd ..
cd ${DEST}/meta-roj-platform
git pull
echo "Updated."

echo "Updated repositories."

